# Generated by Django 5.2.8 on 2025-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_numbers', '0002_rename_authorpublisherinfo_authorpublisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='root',
        ),
        migrations.AddField(
            model_name='aspect',
            name='root',
            field=models.ManyToManyField(related_name='aspects', to='call_numbers.root'),
        ),
    ]
