# Generated by Django 5.2.9 on 2026-04-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("call_numbers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                (
                    "first_page",
                    models.URLField(
                        blank=True,
                        help_text="URL to image of the first page",
                        null=True,
                    ),
                ),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("added", models.DateTimeField(null=True)),
                ("abstract", models.TextField(help_text="May be very large")),
                ("doi", models.CharField(blank=True, null=True)),
                (
                    "call_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="call_numbers.callnumber",
                    ),
                ),
                ("institution", models.ManyToManyField(to="articles.institution")),
            ],
        ),
    ]
