# Generated by Django 5.2.8 on 2025-11-17 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorpublisherinfo",
            options={
                "verbose_name": "author or publisher",
                "verbose_name_plural": "authors and publishers",
            },
        ),
        migrations.RenameField(
            model_name="aspect",
            old_name="subject",
            new_name="root",
        ),
        migrations.RenameField(
            model_name="root",
            old_name="subject",
            new_name="domain",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="subject",
            new_name="aspect",
        ),
    ]
