# Generated by Django 5.2.8 on 2025-11-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_authorpublisherinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
