# Generated by Django 5.2.8 on 2025-11-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_title"),
        ("call_numbers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="aspect",
        ),
        migrations.RemoveField(
            model_name="callnumber",
            name="aspect",
        ),
        migrations.RemoveField(
            model_name="callnumber",
            name="author_pub",
        ),
        migrations.RemoveField(
            model_name="callnumber",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="callnumber",
            name="root",
        ),
        migrations.RemoveField(
            model_name="callnumber",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="callnumber",
            name="topic",
        ),
        migrations.AlterField(
            model_name="article",
            name="call_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="call_numbers.callnumber",
            ),
        ),
        migrations.RemoveField(
            model_name="domain",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="root",
            name="domain",
        ),
        migrations.DeleteModel(
            name="Aspect",
        ),
        migrations.DeleteModel(
            name="AuthorPublisherInfo",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
        migrations.DeleteModel(
            name="CallNumber",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
        migrations.DeleteModel(
            name="Root",
        ),
    ]
