# Generated by Django 5.2.9 on 2026-04-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorPublisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("number", models.CharField()),
            ],
            options={
                "verbose_name": "author or publisher",
                "verbose_name_plural": "authors and publishers",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "number"),
                        name="unique_authorpub_name_and_number",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("number", models.CharField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "number"), name="unique_domain_name_and_number"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Root",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("number", models.CharField()),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roots",
                        to="call_numbers.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("number", models.CharField()),
                (
                    "root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="call_numbers.root",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("number", models.CharField()),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="call_numbers.domain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="root",
            name="subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roots",
                to="call_numbers.subdomain",
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("number", models.CharField()),
                (
                    "aspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="call_numbers.aspect",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CallNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_numbers",
                        to="call_numbers.aspect",
                    ),
                ),
                (
                    "author_pub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_numbers",
                        to="call_numbers.authorpublisher",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_numbers",
                        to="call_numbers.domain",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_numbers",
                        to="call_numbers.root",
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_numbers",
                        to="call_numbers.subdomain",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_numbers",
                        to="call_numbers.topic",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="aspect",
            constraint=models.UniqueConstraint(
                fields=("name", "number", "root"),
                name="unique_aspect_name_number_and_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="subdomain",
            constraint=models.UniqueConstraint(
                fields=("name", "number", "domain"),
                name="unique_subdomain_name_number_and_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="root",
            constraint=models.UniqueConstraint(
                fields=("name", "number", "domain", "subdomain"),
                name="unique_root_name_number_and_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="root",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("domain__isnull", False),
                    ("subdomain__isnull", False),
                    _connector="XOR",
                ),
                name="root_either_domain_or_subdomain",
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("name", "number", "aspect"),
                name="unique_topic_name_number_and_aspect",
            ),
        ),
    ]
