# Generated by Django 5.2.8 on 2025-11-18 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("call_numbers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuthorPublisherInfo",
            new_name="AuthorPublisher",
        ),
    ]
